### ISSUE TITLE
Crafting recipes for attachments giving wrong items

### ISSUE THREAD

**Issue by ItsAegeus** [qbcore-framework/qb-crafting#3]
So after doing some testing I have noticed that some attachment resources give the wrong items on crafting. This is on the latest crafting and core and has been going on since I started the use of QB 2 weeks ago. List of what happens below.

- 1. - > Crafting Shit 
- 2. - > 
- 3. - > level 1
- 4. - > Pistol EXT Clip
- 5. - > Cost~ Scrap-140, Steel-250, Rubber-40
- 6. - > 
- 7. - > Level 2
- 8. - > Pistol Silencer
- 9. - > Cost~ Scrap-165, Steel-285, Rubber-75
- 10. - > 
- 11. - > level 3
- 12. - > SMG Flashlight (Gives Rifle EXT Clip)
- 13. - > Cost~ Scrap-190, Steel-305, Rubber-85, SMG EXT Clip-1
- 14. - > 
- 15. - > Rifle EXT Clip (Gives SMG Scilencer)
- 16. - > Cost~ Scrap-270, Steel-435, Rubber-155
- 17. - > 
- 18. - > Rifle Drummag (Gives SMG Scope)
- 19. - > Cost~ Scrap-300, Steel-469, Rubber-170
- 20. - > 
- 21. - > Level 4
- 22. - > SMG EXT CLip (Need 2 of itself to craft)
- 23. - > Cost~ Scrap-205, Steel-340, Rubber-110, SMG EXT Clip x2
- 24. - > 
- 25. - > Level 5
- 26. - > SMG Silencer (Gives SMG Flashlight)
- 27. - > Cost~ Scrap-230, Steel-365, Rubber-130
- 28. - > 
- 29. - > Level 6
- 30. - > SMG Scope (Gives SMG EXT Clip)
- 31. - > Cost~ Scrap-255, Steel-390, Rubber-145
- 32. - >

**Comment by BerkieBb** [comment]
Should be fixed with commit https://github.com/qbcore-framework/qb-crafting/commit/3c6c5e1e07c8ad7dcebee5574ba97df6a7ad0971
