### ISSUE TITLE
Slot Number

### ISSUE THREAD

**Issue by bosskitz** [qbcore-framework/qb-crafting#4]
There's only one slot for the crafting.

**Comment by bosskitz** [comment]
> There's only one slot for the crafting.

Apologies, I found the reason as to why it's showing just 1 slot.

**Comment by jhovl962** [comment]
> > There's only one slot for the crafting.
> 
> Apologies, I found the reason as to why it's showing just 1 slot.

What was the reason? I’m currently going through the same thing.
