### ISSUE TITLE
items not in shared.lua by default

### ISSUE THREAD

**Issue by RexShack** [qbcore-framework/qb-crafting#7]
you guys are probably still working on this but thought I would highlight just in case

qb-crating breaks due to the following item are not in the shared.lua

rifle_extendedclip (NOT in qbcore/shared.lua)
rifle_drummag (NOT in qbcore/shared.lua)
smg_flashlight (NOT in qbcore/shared.lua)
smg_suppressor (NOT in qbcore/shared.lua)

Additional info:
went to the default location for attachment crafting, pressed [E] and got the following error

![Screenshot 2021-08-17 125140](https://user-images.githubusercontent.com/76662933/129743473-a6e57bfc-5ab8-4aa5-98eb-3557244dd277.jpg)

I removed all the attachments apart from pistol_extendedclip from the qb-crafting / config.lua and qb-inventory / config.lua and it fixed the error... hope it helps.

kind regards
RexshackGaming

**Comment by GhzGarage** [comment]
Been fixed thanks
